//Ingredienti: Pomodori San Marzano, Basilico. Strumenti necessari: Passa pomodori o passaverdure, Pentole grandi dotate di coperchi, Un cucchiaio di legno, Barattoli di vetro, Panni di cotone puliti
		function is_uwu(wannabeuwu)	{
	let uwu = /uwu/ig			;
	if(uwu.test(wannabeuwu))		{
return true					;
						} 
	else 					{
return false					;
						}
						}
		exports.is_uwu = is_uwu		;
//Preparazione: La salsa di pomodoro fatta in casa ha tutto un altro sapore e, per scoprirlo, non vi resta che correre subito al mercato e procuravi una gran quantità di pomodori rossi, maturi e profumati! Questa antica ricetta originale richiede qualche ora di preparazione, ma il risultato sarà così sorprendente che non vi pentirete certo del lavoro fatto, anzi. Prenderete anche voi l’abitudine delle nonne di fare la salsa di pomodoro fatta in casa ogni estate. Se volete saperne di più sulla storia della salsa di pomodoro fatta in casa, scoprite qualche piccola curiosità QUI >> Preparazione Prendete i pomodori di tipo San Marzano, lavateli con cura e taglia teli grossolanamente, eliminando tutte le parti ammaccate; metteteli quindi nelle varie pentole, tenendo conto che non dovranno essere troppo piene o non riuscirete a mescolare bene. Trasferite le pentole sul fuoco e copritele con i relativi coperchi, a fiamma moderata; mescolate frequentemente i pomodori e, quando cominceranno a sobbollire, abbassate ancora la fiamma: fate cuocere i pomodori fino a quando risulteranno poco liquidi. Continuate quindi la cottura ma senza fare addensare troppo la salsa: ricordatevi che, quando la riutilizzerete, la farete cuocere ancora per qualche minuto e si ridurrà ancora un po’. Filtrate quindi i pomodori attraverso il passa pomodoro o il passa verdure: in questo modo eliminerete i semi e la pelle dei pomodori, ottenendo una passata liscia e corposa. Ora potete procedere con la sterilizzazione dei vasetti: in una pentola pulita, fate bollire i vasi di vetro in abbondante acqua per almeno 30 minuti. Per evitare che si rompano, mettete un panno di cotone nella pentola prima di metterla sul fuoco e inserite i lati dello straccio tra i vari vasi. QUI trovate le istruzioni precise per la sterilizzazione dei barattoli >> Trascorsa la mezz’ora necessaria, fate raffreddare i barattoli finché riuscirete a maneggiarli: inserite quindi all’interno un paio di foglie di basilico fresco e versate la passata di pomodoro; chiudete i barattoli ermeticamente, lasciando tra salsa e coperchio un centimetro vuoto. Rimettete i vasetti, ma questa volta a testa in giù, in una pentola con abbondante acqua e fate bollire altri 30 minuti. Questa operazione, anche se un po’ lunga, è assolutamente necessaria per garantire la sterilizzazione e il sottovuoto dei vasetti. Per avere la certezza che si sia effettivamente creato il sottovuoto, premete il coperchio del vaso: se questo rimane immobile è andato tutto bene, se invece sentite “clic” dovrete cambiare tappo e ripetere l’operazione.
